### ISSUE TITLE
Cross-platform CI

### ISSUE THREAD

**Issue by baentsch** [pq-crystals/dilithium#17]
As (intended) downstream consumers (e.g., OQS) run (and test) cross-platform, this should already be done here, too. If no comments to the contrary appear, I'll work on a PR to add CI capabilities for
- [x] Ubuntu
- [x] Debian
- [x] Centos 7
- [x] Centos 8
- [x] Alpine
- [x] OSX
- [ ] Windows

using CircleCI.

**Comment by baentsch** [comment]
Windows templating available. More work, incl. proper use of -mnative, and possible cross-builds (e.g., ARM, Z, Power?), required.

**Comment by gregorseiler** [comment]
Thank you for the suggestion. It is indeed a good idea to automatically run our tests on various platforms. I have now incorporated the same functionality into Travis CI which we are already using. Please also see the comment on the corresponding pull request #18.
