### ISSUE TITLE
Portable build system

### ISSUE THREAD

**Issue by baentsch** [pq-crystals/dilithium#19]
Add CMake build system to
- [x] create Makefiles for different platforms, incl. Win (nmake, VisualStudio) and Ninja (high-speed build)
- [x] permit building static and shared libraries
- [x] permit building cleanly separated namespaces for generic (non-optimized) and optimized variants
- [x] incorporate testing in a platform-independent form (resolving issue #16)

**Comment by gregorseiler** [comment]
Cmake PR #20 merged.
