### ISSUE TITLE
Building without -mnative

### ISSUE THREAD

**Issue by baentsch** [pq-crystals/dilithium#30]
For machine-instruction-optimized code, better control is desirable over which CPU feature flags are set during compilation: For example when moving executables to other machines, the use of `-mnative` during build is risky (as executables can then crash "surprisingly") and should be avoided in favour of setting specific (and documented/"known") CPU feature flags like `-mavx2`. This then also gives a more exact definition of which CPU feature sets are required for optimized code to run and can be specifically tested for, e.g., in CI or cloud environments with different CPU feature sets. 

Therefore, could you please remove this flag as a default setting when building and replace it by specific feature sets required (and as documented in the downstream integration .YML files)?

**Comment by gregorseiler** [comment]
The compiler flag -march=native in the avx2 code is not just there to enable support for the avx2 and aes intrinsics but allows the compiler to make use of whatever (newer) instructions might be available on a specific CPU, for example avx512 instructions. So this should not be replaced by a fixed list of -m flags.
