### ISSUE TITLE
AVX2 code fails in gcc 8/9 on several platforms

### ISSUE THREAD

**Issue by baentsch** [pq-crystals/dilithium#31]
As already reported by email to @gregorseiler : When leaving away `-mnative` (but setting setting the required `-mxyz` options), the AVX2 code fails to pass self- and KAT tests under some circumstances (initial example was gcc 8 under Centos-8).

This is a blocker to resolving issue #30. In addition, this code now also seems to trigger downstream problems with Alpine and OSX (see comments and results of an investigation into the issues [here](https://github.com/open-quantum-safe/liboqs/issues/793)).

This _might_ be a compiler bug - but certainly warrants investigation and either a fix or workaround.

To reproduce, see/use [this Makefile](https://github.com/baentsch/dilithium/blob/gcc8-bug/avx2/Makefile) and use this docker image containing gcc-8: 
```
docker run -v `pwd`:/root/dilithium -it openquantumsafe/ci-centos-8-amd64 bash
```
and execute in that container this minimal build-and-test `cd /root/dilithium/avx2 && make clean && make && cd .. && ./runtests.sh` .

**Comment by baentsch** [comment]
If you do not trust the OQS container, here's a way to create a pristine docker environment to reproduce completely without OQS dependencies:
```
docker run -v `pwd`:/root/dilithium -it centos:8 bash
```
In that container, first deploy tooling to build code by running `yum install -y gcc make openssl-devel`. Then proceed with build-and-test.

**Comment by baentsch** [comment]
Should you further have no trust in the Centos or docker environment, the bug is also reproducible (as initially reported by Douglas) on OSX: Just set CC=gcc-8 and you find the same (signature) verification errors.

Actually, after having installed gcc-8 also in a standard Ubuntu environment, you get the same bug (setting CC=gcc-8): See this branch for most simple reproducibility: https://github.com/baentsch/dilithium/tree/gcc8-bug -- completely without any OQS component/dependency.

**Comment by baentsch** [comment]
Hopefully last update for today: Problem also persists when using gcc-9.

**Comment by gregorseiler** [comment]
Should work now (see PR #35).
