### ISSUE TITLE
Off-by-one error in documentation for reduce32

### ISSUE THREAD

**Issue by SWilson4** [pq-crystals/dilithium#56]
The documentation for `reduce32` states that the output is in the range [-6283009, 6283007]. The range is actually [-6283009, 6283008], as evaluating `reduce32` at 2^{31} - 2^{22} - 1 will illustrate.

I have a branch which fixes both this issue and #55 since they're quite minor.

**Comment by sduyyy** [comment]
@SWilson4 how we evaluate reduce32 at 2^{31} - 2^{22} - 1 ,will you please give a detail description?

**Comment by gregorseiler** [comment]
Thanks. The typos have been corrected
