### ISSUE TITLE
Make PQCgenKAT_sign in RPi4

### ISSUE THREAD

**Issue by tcushion** [pq-crystals/dilithium#58]
On the ARM processor using a 32 bit operating system, the long long type in rng.h, rng.c and PQCgenKAT_sign.c causes a segmentation fault when calling randombytes(seedbuf, SEEDBYTES) for generating the keypair. Changing the type to int appears to fix this although I am unsure if this is stable or optimal for the processor.

**Comment by gregorseiler** [comment]
These files come from NIST
