### ISSUE TITLE
Dilithium3 and Dilithium4 seem to fail on the 21st KAT vector

### ISSUE THREAD

**Issue by sgmenda** [pq-crystals/dilithium#7]
Dilithium3 and Dilithium4 seem to fail (most of the time) on the following message. This message is the 21st KAT vector provided with Dilithium.

[message.txt](https://github.com/pq-crystals/dilithium/files/3189135/message.txt)

**Comment by gregorseiler** [comment]
Hi,

I can not reproduce a problem with this message. Can you please give 
more details about what you did?

Best,
Gregor

**Comment by sgmenda** [comment]
Sorry, my bad. The output message pointer `m` I was passing to `crypto_sign_open` was allocated to `mlen` bytes and not `smlen` bytes.
