### ISSUE TITLE
Possibly wrong macro TRBYTES in crypto_sign_verify standard branch

### ISSUE THREAD

**Issue by marco-palumbi** [pq-crystals/dilithium#75]
**CRHBYTES** macro should be used instead of **TRBYTES**
in:
https://github.com/pq-crystals/dilithium/blob/e29d6eff0319baa14b9ec91d3bd6d912d294951d/ref/sign.c#L255
and:
https://github.com/pq-crystals/dilithium/blob/e29d6eff0319baa14b9ec91d3bd6d912d294951d/ref/sign.c#L257

**Comment by cryptojedi** [comment]
Indeed, thank you very much for pointing this out!
