### ISSUE TITLE
Key size defines in api.h

### ISSUE THREAD

**Issue by sungmin-net** [pq-crystals/dilithium#78]
Hello.
First of all thank you for this job.

According to the below,
https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/xOGBFJNIbEc/m/D_TgPNg6AAAJ 

defines in api.h seems to be updated like the below.

 8 #define pqcrystals_dilithium2_SECRETKEYBYTES 2528 → 2560
 35 #define pqcrystals_dilithium3_SECRETKEYBYTES 4000 → 4032
 36 #define pqcrystals_dilithium3_BYTES 3293 → 3309
 62 #define pqcrystals_dilithium5_SECRETKEYBYTES 4864 → 4896
 63 #define pqcrystals_dilithium5_BYTES 4595 → 4627

Am I correct?

**Comment by gregorseiler** [comment]
The constants have been updated according to the final standard
