### ISSUE TITLE
Incorrect defines in avx2 header

### ISSUE THREAD

**Issue by bhenning10** [pq-crystals/dilithium#89]
The avx2 api.h header does not have size defines for dilithium3, and uses dilithium5 instead. It appears that dilithium5 is also using the draft signature size.

avx2/api.h
> #define pqcrystals_dilithium5_PUBLICKEYBYTES 2592
> #define pqcrystals_dilithium5_SECRETKEYBYTES 4896
> #define pqcrystals_dilithium5_BYTES 4627
> 
> #define pqcrystals_dilithium3_avx2_PUBLICKEYBYTES pqcrystals_dilithium3_PUBLICKEYBYTES
> #define pqcrystals_dilithium3_avx2_SECRETKEYBYTES pqcrystals_dilithium3_SECRETKEYBYTES
> #define pqcrystals_dilithium3_avx2_BYTES pqcrystals_dilithium3_BYTES
> ...
> #define pqcrystals_dilithium5_BYTES 4595

The ref api.h header appears to be correct.

ref/api.h

> #define pqcrystals_dilithium3_PUBLICKEYBYTES 1952
> #define pqcrystals_dilithium3_SECRETKEYBYTES 4032
> #define pqcrystals_dilithium3_BYTES 3309
> 
> #define pqcrystals_dilithium3_ref_PUBLICKEYBYTES pqcrystals_dilithium3_PUBLICKEYBYTES
> #define pqcrystals_dilithium3_ref_SECRETKEYBYTES pqcrystals_dilithium3_SECRETKEYBYTES
> #define pqcrystals_dilithium3_ref_BYTES pqcrystals_dilithium3_BYTES
> ...
> #define pqcrystals_dilithium5_BYTES 4627

**Comment by gregorseiler** [comment]
Yes, indeed. Thanks for reporting
